### ISSUE TITLE
Mending elytra not repairing in trinket slot

### ISSUE THREAD

**Issue by FakeDomi** [emilyalexandra/trinkets#98]
When using the Elytra Trinkets mod, mending elytras cannot repair in the cape slot.

**Comment by FakeDomi** [comment]
Fixed it myself now, feel free to pull the fix in if you want to.

**Comment by PinkGoosik** [comment]
I think it should be merged into elytra trinket mod and not trinkets

**Comment by emilyalexandra** [comment]
Mending is a vanilla behavior and should be working through trinkets itself, it worked in 1.16 but I forgot about  it when I rewrote it for 1.17, it'll get done the next chance I get

**Comment by emilyalexandra** [comment]
Fixed in 3.0.1

**Comment by PinkGoosik** [comment]
pog

**Comment by yesn0t** [comment]
hi, mending elytra still not working most of the time for me, by that i mean XP gained rarely ever goes to mend the elytra;  
i did tests with XP bottles : if i splash 1 xp bottle, while a damaged mending elytra is in trinket slot, then two problems occur :  
* at least 4 out of 5 times the elytra will not be mended
* when it does get mended, the durability gain is 6 points instead of ~18

with elytra in chestplate slot, mending works normally :  
* 100% of the time, elytra is mended by incoming XP
* each mend gives a lot more than 6 points of durability

using `elytratrinket 3.0.0` and `trinkets 3.2.0`  

please let me know if you can reproduce this issue or is if it's just me (._.)'

**Comment by FakeDomi** [comment]
Experiencing the same issue in 3.4.0 still @yesn0t @emilyploszaj
